## Homework



### Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

```python
pd.__version__
```



In [57]:
import pandas as pd
pd.__version__

'2.3.2'

### Q2. Records count

How many records are in the dataset?

- 4704
- 8704
- 9704
- 17704


In [1]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('car_fuel_efficiency.csv')

# Display the DataFrame
print(df)


      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel dr

In [2]:
len(df)

9704

### Q3. Fuel types

How many fuel types are presented in the dataset?

- 1
- 2
- 3
- 4


In [4]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [7]:
set(df['fuel_type'].to_list())

{'Diesel', 'Gasoline'}

In [9]:
df['fuel_type'].nunique()

2

### Q4. Missing values

How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3
- 4

In [12]:
df.isnull().any().sum()
#df.isnull() → returns a DataFrame of the same shape with True where values are NaN.#

#.any() → returns a Series of True/False for each column, indicating if that column has any missing values.

#.sum() → counts the number of True values, i.e., the number of columns with missing values.

4

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

- 13.75
- 23.75
- 33.75
- 43.75

In [23]:
df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].max()

23.759122836520497


### Q6. Median value of horsepower



1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?


- Yes, it increased
- Yes, it decreased
- No

In [32]:
df["horsepower"].median(),df["horsepower"].mode()[0]

(149.0,
 0    152.0
 Name: horsepower, dtype: float64)

In [36]:


df['horsepower'] = df['horsepower'].fillna(152)

print(df['horsepower'].isnull().sum())
df["horsepower"].median()

0


152.0

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.051
- 0.51
- 5.1
- 51


In [48]:
X=df[df["origin"]=="Asia"][["vehicle_weight","model_year"]].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [53]:
XTX=X.T@X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [51]:
import numpy as np
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [55]:
# Compute inverse of (X^T X)
XTX_inv = np.linalg.inv(XTX)

w = (XTX_inv @ X.T)@y
w

array([0.01386421, 0.5049067 ])

In [56]:
w.sum()

0.5187709081074016